import { Inter } from "next/font/google";
import "./globals.css";

import ThemeColorManager from "./components/ThemeColorManager";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <ThemeColorManager />
        <meta name="viewport" content="viewport-fit=cover"></meta>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
